[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "polysolve"
authors = [{name="Terence",email="terence.lobo@stfc.ac.uk"}]
requires-python = ">= 3.8"
readme = "README.md"
description = ""
license = {text = "BSD-3-Clause"}

keywords = ["python"]
dependencies = ["numpy"]
# classifiers = []
dynamic = ["version"]

[project.urls]
Homepage="https://github.com/terencel411/polysolve"
Repository="https://github.com/terencel411/polysolve.git"

[tool.setuptools.dynamic]
version = {attr = "polysolve.__version__"}
